#!/usr/bin/python3

import sys

from launchpadlib.launchpad import Launchpad

lp = Launchpad.login_with('create-rebuild-ppas', 'production', version='devel')

owner = lp.load('/~' + sys.argv[1])

label = sys.argv[2]

ppas = {}

for prefix in 'toolchain', 'livecd-rootfs', 'kernel':
    ppas[prefix] = owner.createPPA(name=prefix + '-' + label)


main_archive = lp.load('/ubuntu').main_archive

for ppa in ppas['kernel'], ppas['livecd-rootfs']:
    for dep in ppa.dependencies:
        ppa.removeArchiveDependency(dep)
    ppa.addArchiveDependency(dependency=main_archive, pocket='Release')

ppas['kernel'].addArchiveDependency(
    dependency=ppas['toolchain'], pocket='Release')
